<?php
/**
 * @file
 * Code for the CA Video Gallery feature.
 */

include_once('ca_video_gallery.features.inc');

/**
 * Implements hook_menu()
 */
function ca_video_gallery_menu() {
/**  $items['admin/config/worx_features'] = array(
    'title' => 'Worx Features',
    'description' => 'Configure Worx Features',
    'position' => 'right',
    'weight' => -20,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );*/
  $items['admin/config/worx_features/video_gallery'] = array(
    'title' => 'Video Gallery Configuration',
    'description' => 'Override settings for ca_video_gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_video_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_video_gallery'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['admin/config/worx_features/video_gallery/general'] = array(
    'title' => 'General Settings',
    'description' => 'Override settings for ca_video)gallery',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ca_video_gallery_settings_form'),
    'access arguments' => array('worx features admin'),
    'file' => 'ca_video_gallery.admin.inc',
    'file path' => drupal_get_path('module', 'ca_video_Gallery'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  
  return $items;
}

/**
 * implements hook_menu_alter().
 */
function ca_video_gallery_menu_alter(&$items) {
  $items['video_gallery']['title'] = variable_get('ca_video_gallery_menu_title', 'Videos');
}